import { Lexend_Deca, Lexend_Zetta, La_Belle_Aurore } from 'next/font/google';
import './styles/globals.css';

const lexendDeca = Lexend_Deca({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  variable: '--font-lexend-deca',
});

const lexendZetta = Lexend_Zetta({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-lexend-zetta',
});

const laBelleAurore = La_Belle_Aurore({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-la-belle-aurore',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>{/* ...existing head elements... */}</head>
      <body className={`${lexendDeca.className} ${lexendZetta.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}