name: Deploy to GitHub Pages (Dev/Staging)

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install

      - name: Build the project for GitHub Pages
        env:
          BASE_PATH: '/dashboard'          # GitHub Pages subpath for this repo
          ASSET_PREFIX: '/dashboard'
        run: |
          yarn build
          yarn export

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out