name: Deploy to GitHub Pages (Dev/Staging)

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install

      - name: Check for missing urls
        run: yarn test

      - name: Build the project for GitHub Pages
        env:
          BASE_PATH: dashboard           # GitHub Pages subpath (no leading slash)
          ASSET_PREFIX: /dashboard       # Asset prefix for images and static files
          NEXT_PUBLIC_ASSET_PREFIX: /dashboard # Ensures client-side code uses correct asset prefix
        run: yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out